--- 
jobs: 
  build: 
    machine: true
    steps: 
      - checkout
      - 
        run: 
          command: "docker pull quay.io/openshift-cs/asciibinder:latest"
          name: "Get AsciiBinder image"
      - 
        run: 
          command: "git branch latest && git checkout latest"
          name: "Set Git branch"
      - 
        run: 
          command: "docker run --rm -it -u `id -u` -v `pwd`:/docs:Z quay.io/openshift-cs/asciibinder asciibinder build --distro \"openshift-enterprise\""
          name: "Build AsciiBinder docs for openshift-enterprise"
      - 
        run: 
          command: |
              sudo cp -v scripts/ocpdocs/_previewpage _preview/index.html && sudo cp -v scripts/ocpdocs/robots_preview.txt _preview/robots.txt;
              sudo zip -r preview.zip _preview/;
              curl -H "Content-Type: application/zip" -H "Authorization: Bearer ${NETLIFY_AUTH_TOKEN}" --data-binary "@preview.zip" https://api.netlify.com/api/v1/sites/ocpdocspreview/deploys;
          name: "Copy files, create zip, upload to Netlify"
version: 2.1
workflows: 
  publish: 
    jobs: 
      - build
