---
jobs: 
  build: 
    machine: true
    steps: 
      - checkout
      - 
        run: 
          command: "docker pull quay.io/openshift-cs/asciibinder:latest"
          name: "Get AsciiBinder image"
      - 
        run: 
          command: "git branch latest && git checkout latest"
          name: "Set Git branch"
      - 
        run: 
          command: "docker run --rm -it -u `id -u` -v `pwd`:/docs:Z quay.io/openshift-cs/asciibinder asciibinder build --distro \"openshift-enterprise\""
          name: "Build AsciiBinder docs for openshift-enterprise"
      - 
        run: 
          command: "sudo cp -v scripts/ocpdocs/_previewpage _preview/index.html && sudo cp -v scripts/ocpdocs/robots_preview.txt _preview/robots.txt"
          name: "Copy files and ZIP"
      - 
        persist_to_workspace: 
          paths: /home/circleci/project/openshift-docs/_preview/
          root: .
  publish: 
    executor: node-executor
    steps: 
      - 
        attach_workspace: 
          at: /tmp/_preview/
      - 
        run: 
          command: "npm install netlify-cli -g"
          name: "Install Netlify CLI"
      - 
        run: 
          command: "netlify deploy --site docspreview --auth $NETLIFY_AUTH_TOKEN --alias $PR_NUMBER --dir=/tmp/_preview/"
          name: "Upload to Netlify"
version: 2.1
workflows: 
  build_and_publish: 
    jobs: 
      - build
      - 
        publish: 
          requires: 
            - build

