jobs:
  build:
    machine: true
    resource_class: medium
    steps:
      - checkout
      -
        run:
          command: "chmod +x scripts/push_to_netlify.sh && ./scripts/push_to_netlify.sh"
          name: "Get PR branch"
      -
        run:
          command: "docker pull quay.io/openshift-cs/asciibinder:latest"
          name: "Get AsciiBinder image"
      -
        run:
          command: "git branch -m latest"
          name: "Set Git branch"
      -
        run: |
          echo "Running asciibinder build for base reference: ${BASE_REF}"
          if [[ "${BASE_REF}" == openshift-enterprise ]]; then
            echo "Running enterprise Asciibinder build"
            docker run --rm -it -u `id -u` -v `pwd`:/docs:Z quay.io/openshift-cs/asciibinder asciibinder build --distro openshift-enterprise
          else
            echo "Running generic Asciibinder build"
            docker run --rm -it -u `id -u` -v `pwd`:/docs:Z quay.io/openshift-cs/asciibinder asciibinder build
          fi
      -
        run:
          command: "docker run --rm -it -u `id -u` -v `pwd`:/docs:Z quay.io/openshift-cs/asciibinder asciibinder build --distro \"openshift-rosa\""
          name: "Build AsciiBinder docs for openshift-rosa"
      -
        run:
          command: "docker run --rm -it -u `id -u` -v `pwd`:/docs:Z quay.io/openshift-cs/asciibinder asciibinder build --distro \"openshift-dedicated\""
          name: "Build AsciiBinder docs for openshift-dedicated"
      -
        run:
          command: "docker run --rm -it -u `id -u` -v `pwd`:/docs:Z quay.io/openshift-cs/asciibinder asciibinder build --distro \"microshift\""
          name: "Build AsciiBinder docs for microshift"
      -
        run:
          command: "wget -O _preview/index.html https://raw.githubusercontent.com/openshift/openshift-docs/main/scripts/ocpdocs/_previewpage && wget -O _preview/robots.txt https://raw.githubusercontent.com/openshift/openshift-docs/main/scripts/ocpdocs/robots_preview.txt"
          name: "Copy files"
      -
        run:
          command: "npm install netlify-cli -g"
          name: "Install Netlify CLI"
      -
        run:
          command: "netlify deploy --site docspreview --auth $NETLIFY_AUTH_TOKEN --alias $PR_NUMBER --dir=_preview/"
          name: "Upload to Netlify"
      - jq/install
      -
        run:
          command: "wget https://raw.githubusercontent.com/ocpdocs-previewbot/openshift-docs/main/scripts/ghcomment.sh && chmod +x ghcomment.sh && ./ghcomment.sh"
          name: "Add comment on PR"

orbs:
  jq: circleci/jq@2.2.0
version: 2.1
workflows:
  build_and_publish:
    jobs:
      - build
